vconn: Fix using of uninitialized deadline.
Typo introduced while making minor refactoring before applying the
patch.

Fixes logic and the clang build:

  lib/vconn.c:707:47: error:
      variable 'deadline' is uninitialized when
      used within its own initialization [-Werror,-Wuninitialized]
                              ? time_msec() + deadline
                                              ^~~~~~~~

Acked-by: Kevin Traynor <ktraynor@redhat.com>
Fixes: 04895042e9f6 ("vconn: Allow timeout configuration for blocking connection.")
Signed-off-by: Ilya Maximets <i.maximets@samsung.com>
Signed-off-by: Ben Pfaff <blp@ovn.org>