ofp-parse: Include missing ofp-actions.h.
This fixes MacOS build:

  lib/ofp-parse.c:167:16:
          error: use of undeclared identifier 'IPPORT_FTP'

  lib/ofp-parse.c:171:16:
          error: use of undeclared identifier 'IPPORT_TFTP'

CC: Ben Pfaff <blp@ovn.org>
Fixes: 0d71302e36c4 ("ofp-util, ofp-parse: Break up into many separate modules.")
Signed-off-by: Ilya Maximets <i.maximets@samsung.com>
Signed-off-by: Ben Pfaff <blp@ovn.org>