osx: Fix compilation error.
The commit "northd: Add ECMP support to router policies." introduced
compilaton error on osx platform.  This patch fixes the issue.

The errors are:

----
northd/ovn-northd.c:7697:38: error: format specifies type 'unsigned short'
but the argument has type 'int' [-Werror,-Wformat]
                      ecmp_group_id, i + 1);
                                     ^~~~~
northd/ovn-northd.c:7713:44: error: format specifies type 'unsigned short'
but the argument has type 'int' [-Werror,-Wformat]
        ds_put_format(&actions, "%"PRIu16, i + 1);
                                 ~~~~~~~~  ^~~~~
----

Fixes: 35b00c7e7990("northd: Add ECMP support to router policies.")
Suggested-by: Dumitru Ceara <dceara@redhat.com>
Signed-off-by: Numan Siddique <numans@ovn.org>